language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t lstas180877/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lstas180877/react-test npm run test

after_success:
  - docker build -t lstas180877/multi-client:v1 ./client
  - docker build -t lstas180877/multi-nginx:v1 ./nginx
  - docker build -t lstas180877/multi-server:v1 ./server
  - docker build -t lstas180877/multi-worker:v1 ./worker

# Log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push lstas180877/multi-client:v1
  - docker push lstas180877/multi-nginx:v1
  - docker push lstas180877/multi-server:v1
  - docker push lstas180877/multi-worker:v1


#deploy:
#  provider: elasticbeanstalk
#  region: us-east-2
#  app:  multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-east-2-495010293839
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
#
#
